In [ ]:
import numpy as np

In [ ]:
a = np.random.randint(11, size=(3,3))
b = np.random.randint(11, size=(3,3))
print(a)
print(b)

[[ 3 10  8]
 [ 6  4  2]
 [ 2  5  5]]
[[7 1 7]
 [4 9 5]
 [2 8 2]]


In [ ]:
mul = np.multiply(a, b)
print(mul)

[[21 10 56]
 [24 36 10]
 [ 4 40 10]]


In [ ]:
eyefour = np.eye(4)
print(eyefour)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
nordis = np.random.normal(10, 5, size=(3, 3))
print(nordis)

[[15.43341658 20.0889215  11.48603937]
 [ 1.69822318  8.60953969  8.74736077]
 [10.11744979 14.62492877 14.45307264]]


In [ ]:
print(a)
transposea = np.transpose(a)
print(transposea)

[[ 3 10  8]
 [ 6  4  2]
 [ 2  5  5]]
[[ 3  6  2]
 [10  4  5]
 [ 8  2  5]]


Numpy vectorizes some computations by having some precompiled c code that makes the runtime significantly less. 


In [ ]:
lambdafunction = np.fromfunction(lambda i, j: i*j, (3, 3))
print(lambdafunction)

[[0. 0. 0.]
 [0. 1. 2.]
 [0. 2. 4.]]


In [ ]:
print(a)
print(np.sum(a))
aprime = np.empty_like(a)

co1 = 0
for i in a:
  co2 = 0
  for j in i:
    aprime[co1, co2] = j*2
    co2 += 1
  co1 += 1
print(aprime)
print("doubled each element in array by 2")

[[ 3 10  8]
 [ 6  4  2]
 [ 2  5  5]]
45
[[ 6 20 16]
 [12  8  4]
 [ 4 10 10]]


Numpy vectorization is a pathway to parallelization becasue the code is already compiled and is done before you even get to use it. This parallelizes it becasue it divides the tasks by compiling the function you would use, for later use. Since its compiled code, its faster. 